project:
  type: website
  output-dir: docs
website:
  title: "EEID2024"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: materials.qmd
        text: Materials

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



